CREATE TABLE public.review (
    review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    review_text text NOT NULL,
    review_date timestamp with time zone NOT NULL DEFAULT now(),
    inv_id integer NOT NULL,
    account_id integer NOT NULL,
    CONSTRAINT review_pkey PRIMARY KEY (review_id),
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES public.account (account_id) ON UPDATE CASCADE ON DELETE NO ACTION
);